podcast:
  basic-path: D:/podcast

spring:
  thymeleaf:
    cache: false
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlite:${podcast.basic-path}/mydatabase.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      max-wait: 60000


mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mapper/**/*Mapper.xml